### ISSUE TITLE
Interceptor blocking all input when using wireless devices

### ISSUE THREAD

**Issue by dafzor** [oblitum/Interception#139] opened 2022-04-05 22:45 UTC
This is a copy of https://github.com/cajhin/capsicain/issues/70

I've been using capsicain for a few weeks now and started to get an issue when resuming from sleep were I'd no longer be able to use any of my input devices after switching to mainly wireless  (mix of bluetooth and 2.4g wireless)keyboards and mouses.

I'm still not 100% sure it's capsicain bug, but all points to it and have not had the issue since uninstalling the interception driver which was 5 days ago (if it happens again without capsicain I'll close this issue).

The behavior is as following:

- After waking up from a long sleep occasionally keyboard input would no longer work
- Plugging in a new usb keyboard would also not work
- Unpluging HID devices that were still working (keyboard or mouses) and plugging them back in would also make them stop working
- Before windows loaded the keyboard would work normally (i wake up from sleep by keyboard key press)
- Using Wireshark usb sniffer I could see usb package from the keyboard being received like it was working normally, however input would be registered
- Restarting capsicain would not fix the lack of input
- Rebooting the computer would make input work normally again

So summarizing, after windows slept for a long time any input device that disconnected would no longer register any input until the computer rebooted again. The input device would still be connected to the computer, send USB packages with data but no input would be registered until rebooting.

**Comment by dafzor** [comment] 2022-04-05 22:55
Just saw #133  which seemed to have similar behavior and could be related with this.

I'm however using latest Windows 10 with TPM 2.0 enabled, Secure Boot disabled and was using it without issue until adding new wireless input devices.

**Comment by oblitum** [comment] 2022-04-10 01:27
This is a duplicate of #25, same response as in #140. After resuming the devices counters for all devices probably increase (as in a reconnect) beyond current limit.

**Closed as completed by oblitum** 2022-04-10 01:27 UTC
