### ISSUE TITLE
Ran installer /install, rebooted, can't use any mouse or keyboard.

### ISSUE THREAD

**Issue by stfamse** [oblitum/Interception#86] opened 2019-10-03 13:14 UTC
I ran the installer from an administrator command line, as instructed. Rebooted and now neither mouse or keyboard work from startup. Lock screen comes up, clock is working fine, so it isn't frozen. Just can't move the mouse or press any keys. Tried to /uninstall from the command prompt inside Windows Advanced Options Troubleshoot Command Prompt but an error about systems not being loaded, as is the case with most things I try to do from there.

I am on Windows 8.1 64-bit Home. Tried several backup mice and keyboards, I am littered with them but to no avail. If my understanding of the programming was correct, I shouldn't be blocked out at this early of a point, should I?

Any ideas on what might have happend? How I might be able to /uninstall? Should I bite the bullet and do a Window Refresh? Will that even help?

**Comment by oblitum** [comment] 2019-10-03 17:18
Hi. I can't know why that happened for you, no idea. This is duplicate of #83, you should read  what happened there.

**Closed by oblitum** 2019-10-03 17:18 UTC
