### ISSUE TITLE
Interception driver stops keyboard and mouse from working.

### ISSUE THREAD

**Issue by inGyni** [oblitum/Interception#117] opened 2021-04-18 17:39 UTC
After installing the interception driver, like usual, thru the "install-interception.exe /install" (in admin cmd) and then restarting my pc, I cannot use my keyboard and mouse, even in safe mode.
I tried going into windows recovery and renaming the interception folder to something else in hopes of stopping it from loading, seems like that is also not working. Can someone help me out on this?

**Comment by oblitum** [comment] 2021-04-18 17:46
If you're able to log the machine through recovery, the recommended procedure is to execute `install-interception.exe /uninstall`. In case you corrupted the installation manually by deleting system files, etc, then you can try executing `install-interception.exe /install` to recover original state, and then run `install-interception.exe /uninstall` in sequence.

Duplicate of #83.

**Closed by oblitum** 2021-04-18 17:46 UTC

**Comment by inGyni** [comment] 2021-04-18 17:53
I did this already, it says my windows is not compatible with this installer.

**Comment by oblitum** [comment] 2021-04-18 18:02
So for some reason the installer is not detecting what windows is it from recovery and exiting, which is weird... The last manual option then is to remove all references to the drivers from registry with `regedit`.
[This zip](https://github.com/oblitum/Interception/files/6331893/Interception-necessary-configuration.zip) contain all the manual details for remotion.

**Comment by hugmeagn** [comment] 2024-01-04 14:48
vanguard (or another anti-cheat) may be involved in this. I don't think there's anything the interception driver developer can do about it. https://www.reddit.com/r/VALORANT/comments/genkxg/support_guide_to_fix_vanguard_disabling_mouse/
