### ISSUE TITLE
WARNING: Breaks mice and keyboards on KVM

### ISSUE THREAD

**Issue by Slion** [oblitum/Interception#145] opened 2022-06-12 15:58 UTC
Interception closed source driver can break mice and keyboards in some nasty way when using a KVM switch such has the one built-in Dell U3818DW.

Basically after the KVM switches back to a PC with Interception installed mice and keyboards can stop working. To get them to work again I need a reboot through BIOS.

Bug is confirmed on Windows 10. Motherboard is an Asus Z270-WS. Since devices often won't start working again until I boot to the BIOS I'm thinking Interception could be causing a fairly low level issue that somehow disables a device at the motherboard level.

See that [reddit post](https://www.reddit.com/r/LogitechG/comments/uv6i3i/g903_wireless_stops_working_after_dell_u3818dw/) where I described my issue.

**Comment by PeyPal** [comment] 2022-06-27 22:26
Can confirm I am having the same issue. It happens with my KVM built into my Gigabyte M27Q monitor and even if I just unplug my keyboard completely.

I would also like to add that after toggling between PCs with the KVM any separate keyboard or mouse plugged directly into the PC do not work. And to top it off, I have my mouse plugged into my a USB pass through port on my keyboard, switching back and forth on the KVM once will disable my keyboard completely but allow my mouse to work. After switching a second time my mouse gets disabled.

This persists until I do a reboot. I also have an Asus MOBO, but have not needed to boot to BIOS first in order to get my keyboard or mouse to work again. I should also mention that I do have a Logitech mouse, but I have a wired Logitech G503 Hero.

After uninstalling the Interception driver I have had 0 issues with my KVM and until I get my flight stick back from RMA it'll be staying that way...

**Comment by oblitum** [comment] 2022-06-27 22:36
This most probably is a duplicate of #25 like many others. The reason behind is well known. After some hiatus I'm taking a look to fix this currently. If a solution is reached I'll kindly ask to try it again, if there's still interest.

**Closed as not planned by oblitum** 2022-06-27 22:36 UTC

**Comment by Slion** [comment] 2022-06-28 07:08
@oblitum Closing this as a duplicate is not helping people coming here understand this major issue. I mean the thing just prevents you to use your computer and can force you doing a hard reset. If anything you should pin it to make sure it is visible.
I have personally wasted days trying to fix it and would have appreciated a very prominent WARNING about it.
Though I understand strictly speaking it is a duplicate.

Also the other issue is locked, that seems to prevent auto-link to this issue.

**Comment by danielfullerton** [comment] 2022-12-29 18:59
So glad I found this (and the Reddit post). I spent hours trying to figure out why my keyboard would stop working and needed a full reboot as a result. I use a KVM to switch between a couple PCs, and after some troubleshooting, ultimately found that plugging/unplugging my keyboard 3+ times would cause this issue. Had no clue what was causing it until I found this and the Reddit thread. Unfortunate too, because I was using Interception heavily, but this con outweighs the pros for me. A prominent warning in the README or elsewhere really is needed.

**Comment by paulpv** [comment] 2024-10-15 09:41
A simple comment in the readme would help a ton here to save people from wasting their time.

I too have wasted my time after days of personal hobby development time.
I got things working really really well where I just happened to not be using my KVM (I must have been very focused).
I then took a break over a weekend, and when I powered on my PCs a couple of days later, without even firing up the code that I had been working on, I started to use my KVM to swap back and forth and then the keyboard and mouse just stopped working.
It took me almost another full day to finally confirm the problem was Interception.

This is all a personal hobby of mine.
No way am I able to afford both a $2,200 license fee plus obtaining my own signing certificate.

I understand this costs @oblitum too, both time and fiat, and am appreciative of his past and any current and future work on this.
This fix is known (#25), it just seems like it is a matter of a little coding time and signing for oblitum.

It seems like there could be some way to update this and be a win:win for everyone involved and/or interested.

☮️
