### ISSUE TITLE
Connecting new device makes it not working.

### ISSUE THREAD

**Issue by AlexMKX** [oblitum/Interception#45] opened 2017-03-01 07:03 UTC
I use my laptop with MS Sculpt Ergonomic desktop (wireless mouse + keyboard). After connect/disconnect, which I'm doing several times per day, I have firstly mouse stopped working, and then keyboard too. Not only userspace filtering app  stopped from receiving messages from interception, but keyboard and mouse don't work entirely. Stopping or disabling userspace program don't solves issue. After interception driver uninstallation it started working as expected.

**Comment by oblitum** [comment] 2017-03-01 23:52
Duplicate of #25.

**Closed by oblitum** 2017-03-01 23:52 UTC
