### ISSUE TITLE
Seeking clarity on claims of "$2000 to remove 10-device limit"

### ISSUE THREAD

**Issue by evilC** [oblitum/Interception#62] opened 2018-03-08 01:31 UTC
As you may be aware, there is a rather popular [YouTube video series](https://www.youtube.com/watch?v=Hn18vv--sFY) about multiple keyboard macros, where Interception was fingered as a source of device malfunctions due to it improperly handling too many devices (Not my claims, trying to sum up what was said in the video).  
Can you elaborate as to whether you think there is any possibility of failures when using large numbers of USB devices?  
WRT to the 10-device limit (Which, as he points out, when some physical keyboards create 4 devices apiece, suddenly means 2 is your limit before problems occur), is it a simple case of upping `INTERCEPTION_MAX_KEYBOARD 10` in `interception.h`, recompiling and signing? Would you have any objection to me doing so? (I know someone who can sign drivers)  
I am hoping we can come to some solution here which does not wreck your revenue stream, but clearly the amounts being banded about are way out of the reach of enthusiasts.

**Comment by oblitum** [comment] 2018-03-08 02:15
Duplicate of #25. Everything about this is there and it was already locked.

**Closed by oblitum** 2018-03-08 02:15 UTC
