### ISSUE TITLE
Is interception still in development?  If so, has the device limit been removed?

### ISSUE THREAD

**Issue by zachary-D** [oblitum/Interception#63] opened 2018-03-08 17:50 UTC
(assuming the project is still in development)

Back in May you mentioned you were hoping to remove the device limit, but weren't able to for driver signing reasons (link: https://github.com/oblitum/Interception/issues/25#issuecomment-308621404).  I was wondering if the limit has been removed.  I'd love to be able to use interception, but I've got a lot of USB devices and I've heard that causes issues.

**Comment by oblitum** [comment] 2018-03-08 17:54
It has not been removed. There's no ETA on delivering that.

Closed as duplicate of #25. Everything about this is there and it was already locked.

**Closed by oblitum** 2018-03-08 17:54 UTC

**Comment by oblitum** [comment] 2018-03-13 07:12
[Check this comment](https://github.com/oblitum/Interception/issues/25#issuecomment-372567991) for more information on this topic.
