### ISSUE TITLE
With too many HIDs, some of them stop working.

### ISSUE THREAD

**Issue by TaranVH** [oblitum/Interception#50] opened 2017-06-13 22:45 UTC
I have 7 keyboards/numpads plugged in right now, and 12 USB devices overall.
[http://i.imgur.com/udq3WWK.jpg](http://i.imgur.com/udq3WWK.jpg)
I use interception and a command-line tool called intercept.exe to reprogram these extra keyboards, so that I can use AutoHotKey to turn them into multipurpose macros.
(All you never wanted to know about my process for doing that can be found here: https://www.youtube.com/watch?v=y3e_ri-vOIo)

The problem, however, is that ever since I installed interception, my USB devices are not recognized unless they were already plugged in when I booted the computer. (Windows 10, 64 GB RAM, Intel i7-6950X)

FURTHERMORE, sometimes some of my keyboards or other USB devices are not recognized at all, even if they WERE plugged in when the computer is rebooted.

Also, often the 18 macro keys on my Logitech G15 keyboard will NOT work at all, even though the regular keys DO work. And I've had the exact same problem with my new Corsair K95 RGB.

I believe this is related to interception, because I tried uninstalling it, and then all my devices were recognized with no issues. I installed the latest version (v1.0.1) and my issues returned.

Right now, the only way for me to fix this is to have far fewer USB devices plugged in, and/or to reboot until the correct ones are recognized.

Let me know if this is fixable, or if you need any further information. Thanks!

**Comment by oblitum** [comment] 2017-06-14 06:22
Duplicate of #25

**Closed by oblitum** 2017-06-14 06:22 UTC
