### ISSUE TITLE
Some key not intercepted

### ISSUE THREAD

**Issue by neoedmund** [oblitum/Interception#58] opened 2018-01-19 05:35 UTC
Some key not intercepted: 
<kbd>/</kbd> on numpad
<kbd>Enter</kbd> on numpad
<kbd>insert</kbd> `home` `pageUp`
<kbd>delete</kbd> `end` `pageDown`
<kbd>left arrow</kbd> `right arrow`
<kbd>up arrow</kbd> `down arrow`

**Comment by oblitum** [comment] 2018-01-20 00:24
Duplicate of #2. Check there for procedure to verify whether Interception is in the stack for capturing those keys on your keyboard.

**Closed by oblitum** 2018-01-20 00:24 UTC

**Comment by neoedmund** [comment] 2018-01-20 00:42
Well, I use `INTERCEPTION_FILTER_KEY_ALL` instead of `INTERCEPTION_FILTER_KEY_DOWN | INTERCEPTION_FILTER_KEY_UP` seems solve the problem. 
I suggest maybe you could update the sample code with `INTERCEPTION_FILTER_KEY_ALL` for less confusing.
