### ISSUE TITLE
can't use keyboard&mouse when login in win10 after restart

### ISSUE THREAD

**Issue by ColaMachine** [oblitum/Interception#94] opened 2019-12-18 08:41 UTC
After I executed the command install-interception.exe /install and then  restart the computer, I stuck in the win10 login interface. I found that I couldn't use my keyboard and mouse. The only key I could press was the power key on my computer. At last, I had to reinstall my win10 system

**Comment by oblitum** [comment] 2019-12-18 13:59
Duplicate of #83.

**Closed by oblitum** 2019-12-18 13:59 UTC
