### ISSUE TITLE
Interception fails to install

### ISSUE THREAD

**Issue by Jackpen7** [oblitum/Interception#48] opened 2017-05-05 04:21 UTC
When attempting to install Interception on 64 Bit Windows 10 Pro, it fails with the error Unable to write to \system32\drivers. I am running it in an elevated command prompt and I even tried it in Safe Mode, all to no avail.

**Comment by oblitum** [comment] 2017-05-05 04:25
Please try again after rebooting and not opening the drivers folder with Windows Explorer. Sometimes Windows obtain locks that prevents this, but this is quite rare to happen. If you tried already, I'm sorry but I can have no idea what's happening on your system. Safe mode is not necessary, just cmd.exe as administrator once for install or uninstall.

**Comment by oblitum** [comment] 2017-05-05 04:26
I also run it on Windows 10 Pro 64 bit Creators Update, as well as other users.

**Comment by Jackpen7** [comment] 2017-05-05 04:27
Thanks for the fast response. I have tried both of those things, and it still will not install. Likewise, I am using the creators update. Is there any way I can manually install the drivers?

**Comment by oblitum** [comment] 2017-05-05 04:36
Sorry but no, only by checking driver sources which are available by license purchase. I will check the installer again as soon as I get to Windows, after applying any pending updates, to see whether any update brings any conflict. In case I'm unable to find any issue I'll close this ticket as "unable to reproduce".

**Comment by Jackpen7** [comment] 2017-05-05 04:37
How much is a license purchase?

**Comment by oblitum** [comment] 2017-05-05 04:38
There are two licenses which prices that you may check in README.

**Comment by Jackpen7** [comment] 2017-05-05 04:38
OK thanks

**Comment by Jackpen7** [comment] 2017-05-05 04:41
Thanks for all the help. If it is any use, I am trying to use Interception for this: [2nd-Keyboard](https://github.com/TaranVH/2nd-keyboard)

**Comment by oblitum** [comment] 2017-05-05 04:45
OK.

**Comment by Jackpen7** [comment] 2017-05-05 18:58
Apperently, it installed anyway, as my 2nd KB works as expected

**Comment by oblitum** [comment] 2017-05-05 18:59
OK, so closing.

**Comment by Jackpen7** [comment] 2017-05-05 18:59
Thanks for all the help!!

**Closed by oblitum** 2017-05-05 18:59 UTC
