### ISSUE TITLE
Request to open-source the installer

### ISSUE THREAD

**Issue by tpiekarski** [oblitum/Interception#128] opened 2021-11-14 18:41 UTC
Can I ask why the installer is closed source?
Could you consider to open source it?

When this is not an option at all, could you point out if it is possible to install it manually like other regular drivers? And at least describe the steps involved. I do not like to run an installer who could brick my rig, like I read about in other few issues without knowing what this installer is doing.

No offense but to be honest I am wondering you got an open source project with a closed source installer, now that's a little bit odd, isn't it.

**Comment by oblitum** [comment] 2021-11-14 18:51
See https://github.com/oblitum/Interception/issues/117#issuecomment-822033349.

Closing as duplicate of https://github.com/oblitum/Interception/issues/120. I see nothing odd with it.

**Closed as completed by oblitum** 2021-11-14 18:51 UTC

**Comment by oblitum** [comment] 2021-11-14 18:57
FWIW, I dogfood on this project since Windows 2000 till Windows 10 20H2, on every OS upgrade, no issues, working rocksolid as expected. But nothing is perfect, when people report, it's generally in very rare/narrow situations which I'm unable to replicate, or they did something wrong, picked the software from 3rd party, don't know how to program, etc.

**Comment by tpiekarski** [comment] 2021-11-14 19:12
Sounds reasonable, thanks for your reply. Didn't know you make to some degree a living of it.
Going to reconsider and giving a shot in a VM, I am intrigued by the library and possible use-case in the Qt framework :-)
