### ISSUE TITLE
INTERCEPTION DEVICE LIMIT

### ISSUE THREAD

**Issue by CHOKSTARMUSIC** [oblitum/Interception#140] opened 2022-04-08 03:22 UTC
Anyway that the device limit will be increased?
I have read everywhere.

The owner here said, 3 years ago, that he might relelase a driver with more device limit.
Is it really happening?

**Comment by oblitum** [comment] 2022-04-10 01:24
Duplicate of #25. I'm sorry, but state is still the same. I'm still open to solve this, when time and funding arrives for it.

**Closed as completed by oblitum** 2022-04-10 01:24 UTC
