### ISSUE TITLE
interception_receive always returns less than or equal to 0

### ISSUE THREAD

**Issue by Xavier-YangCN** [oblitum/Interception#102] opened 2020-07-19 02:18 UTC
I tried to run the sample codes, but it always exit after a flash of the command window. By adding some pause I find that the loop is always skipped, eg while(interception_receive(context, device = interception_wait(context), (InterceptionStroke *)&stroke, 1) > 0), while I don't press any key. I read most issues but still don't find how this problem occurs. Thanks!

**Comment by Xavier-YangCN** [comment] 2020-07-19 02:35
maybe there is something wrong when I run the installer? I run it as administrator and it just also behave as a flash of the command line window, and there is no log file so I don't know if I install it correctly...Sorry for bother you with so fundamental problem

**Comment by Xavier-YangCN** [comment] 2020-07-19 09:25
I found that the there is something wrong in create_context, but I don't know why...is there any other environment needed except for WDK?

**Comment by oblitum** [comment] 2020-07-19 19:45
The only think necessary to built examples is the WDK, but you actually don't need it if you're simply linking and using the library, you can use whatever build system for that. You have to install drivers as instructed, you're issue seems duplicate of previous one where the driver isn't installed.

**Closed by oblitum** 2020-07-19 19:45 UTC

**Comment by Xavier-YangCN** [comment] 2020-07-20 00:01
Thanks! I got so stupid problem since I'm not familiar with windows command line...the problem is solved now
