### ISSUE TITLE
Send keys to background window

### ISSUE THREAD

**Issue by Saltless0** [oblitum/Interception#97] opened 2020-05-03 05:44 UTC
Is there a method to send keys not opened window.

**Comment by xtremertx** [comment] 2020-05-04 08:09
Doing keylogger?

**Comment by byquip** [comment] 2020-05-21 07:31
> Is there a method to send keys not opened window.

Also interested in this.

> Doing keylogger? 🗡️

For my case it's an automatization tool.

**Comment by oblitum** [comment] 2020-07-02 17:23
Duplicate of #43.

**Closed by oblitum** 2020-07-02 17:23 UTC
