### ISSUE TITLE
Issue unistalling the driver 

### ISSUE THREAD

**Issue by Drgreenspon** [oblitum/Interception#99] opened 2020-06-03 17:54 UTC
Hi there i installed the driver form testing a mouse acceleration app after a few days i tried to unistall the interception driver but im facing this error

![Untitled](https://user-images.githubusercontent.com/66382713/83670792-fe383380-a5d3-11ea-942e-ed2fe8a7bdee.png)
![Untitled2](https://user-images.githubusercontent.com/66382713/83670794-fed0ca00-a5d3-11ea-8ca2-f67171f7b277.png)

**Comment by oblitum** [comment] 2020-06-03 22:32
Can't reproduce.

Just verified install and uninstall on latest Windows with all latest updates.

Closing as it's not using official install sources and this repository is about support for library users, not 3rd party tools.

**Closed by oblitum** 2020-06-03 22:32 UTC
